CREATE TABLE workouts (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    done BOOLEAN NOT NULL DEFAULT 0
);
CREATE TABLE training_days(
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	type VARCHAR(255) NOT NULL,
    done BOOLEAN NOT NULL DEFAULT 0
);
