CREATE TABLE workouts (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
    ui_name VARCHAR(255) NOT NULL,
    description TEXT, 
    type_id INT(6) UNSIGNED NOT NULL,
    focus_id INT(6) UNSIGNED NOT NULL,
    difficulty_id INT(6) UNSIGNED NOT NULL
);
CREATE TABLE types(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    value VARCHAR(255) UNIQUE NOT NULL,
    ui_value VARCHAR(255)
);
CREATE TABLE focuses(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    value VARCHAR(255) UNIQUE NOT NULL,
    ui_value VARCHAR(255)
);
CREATE TABLE diffculties(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    value VARCHAR(255) UNIQUE NOT NULL,
    ui_value VARCHAR(255)
);
